#' @title Decision Forest algorithm: Model prediction wiht DFp2
#' @description Decision Forest algorithm: Model prediction with constructed DF models.
#'   DT_models is a list of Decision Tree models (rpart.objects) generated by DF_train()
#'   DT_train_CV() is only designed for Cross-validation and won't generate models
#'
#'
#' @param DT_models Constructed DF models
#' @param X Test Dataset
#' @param Y Test data endpoint
#'
#' @return  .$accuracy:      Overall test accuracy
#' @return  .$predictions:    Detailed test prediction
#'
#' @importFrom class knn
#'
#' @export
#'
#' @examples
#'   data(demo_simple)
#'   X = Data_simple$X
#'   Y = Data_simple$Y
#'   names(Y)=rownames(X)
#'
#'   random_seq=sample(nrow(X))
#'   split_rate=3
#'   split_sample = suppressWarnings(split(random_seq,1:split_rate))
#'   Train_X = X[-random_seq[split_sample[[1]]],]
#'   Train_Y = Y[-random_seq[split_sample[[1]]]]
#'   Test_X = X[random_seq[split_sample[[1]]],]
#'   Test_Y = Y[random_seq[split_sample[[1]]]]
#'
#'   used_model = DF_train(Train_X, Train_Y,stop_step=4, Method = "MCC")
#'   Pred_result = DF_pred(used_model,Test_X,Test_Y)
#'   DF_ConfPlot(Pred_result, Test_Y, bin = 40)
#'
#'
#'
DFp2_pred = function(used_model, Train_X, Train_Y, Test_X, Test_Y=NULL, k=5){
  # this is only for DFp2 method!
  models = used_model[,"Used Feature"]
  pred=c()
  for (i in 1:length(models)){
    if (used_model[i,"In Final Model"] == "In" ){
      pred = cbind(pred,as.matrix(knn(train=Train_X[,models[[i]]],cl=Train_Y, test=Test_X[,models[[i]]],k=k)))
    }
  }
  if (ncol(pred)==1){
    pred_table = pred
  }else{
    pred_table = apply(pred,1,function(x) names(table(x))[which.max(table(x))])
  }

  performance = DF_perf(pred_table,test_label)

  return(performance)
}
